"""Table for the "prefix KV in full precision" probe, scalar and vector variants (pre-registered research/lab_log.md 2026-09-10).

  python scripts/prefix_kv_table.py [--dir results/raw/prefixkv_local]

Vector rows: `results.jsonl` of gptvq_harrier.py (fields gt_ndcg10 / q_cos_fp and *_pkv0 / *_pkv1), per-query nDCG in
`perq/<name>.npz` (keys ndcg, ndcg_pkv0, ndcg_pkv1).  Scalar rows: `exports.jsonl` of gptq_export_gguf.py --no_gguf
(torch_ndcg[dataset] with the same keys), per-query in `perq/<dataset>_<tag>_<splits>.npz`.  pkv0 = the whole prompt's K/V from
the fp model, pkv1 = only the first (sink) token from fp.  Paired by construction (same quantised model, same queries);
bootstrap 10 000 draws, seed 0.  Writes results/tables/prefix_kv.md.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np

sys.stdout.reconfigure(encoding="utf-8")
ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT / "scripts"))
from eq.graph_metrics import paired_bootstrap  # noqa: E402
try:
    from vq_graded_table import npz_name  # noqa: E402  (per-query file names of the VQ rows; the VQ quantizer is not in the public package)
except ImportError:
    npz_name = None

N_BOOT, SEED = 10000, 0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dir", default="results/raw/prefixkv_local")
    ap.add_argument("--out", default="results/tables/prefix_kv.md")
    a = ap.parse_args()
    d = ROOT / a.dir
    entries = []   # (label, dataset, n, fp, plain nDCG, plain cos, {n_fp: (nDCG, cos, cos_to_plain, P, perq)}, perq_plain)
    p = d / "results.jsonl"
    if p.exists() and npz_name is not None:
        for line in open(p, encoding="utf-8"):
            r = json.loads(line)
            if "q_cos_fp_pkv0" not in r:
                continue
            z = np.load(d / "perq" / npz_name(r))
            pk = {n: (r[f"gt_ndcg10_pkv{n}"], r[f"q_cos_fp_pkv{n}"], r[f"cos_plain_pkv{n}"], r[f"prefix_tokens_pkv{n}"], z[f"ndcg_pkv{n}"]) for n in (0, 1, -1) if f"gt_ndcg10_pkv{n}" in r}
            entries.append((f"VQ {r['bits']} b (dim 4, {r['eff_bpw']:.2f} bpw, seed {r['rot_seed']})", r["teacher"], r["dataset"], r["calib"], r["n_queries"], r["fp_ndcg10"], r["gt_ndcg10"], r["q_cos_fp"], pk, z["ndcg"]))
    p = d / "exports.jsonl"
    if p.exists():
        for line in open(p, encoding="utf-8"):
            r = json.loads(line)
            for ds, t in r.get("torch_ndcg", {}).items():
                if "q_cos_fp_pkv0" not in t:
                    continue
                z = np.load(d / "perq" / f"{ds}_{r['tag']}_{r['splits']}.npz")
                pk = {n: (t[f"ndcg10_pkv{n}"], t[f"q_cos_fp_pkv{n}"], t[f"cos_plain_pkv{n}"], t[f"prefix_tokens_pkv{n}"], z[f"ndcg_pkv{n}"]) for n in (0, 1, -1) if f"ndcg10_pkv{n}" in t}
                teacher = r.get("teacher") or ("jina-v5-small" if "legal-cs" in r["calib"] else "harrier-0.6b")   # rows written before the field existed (2026-09-10 queue)
                entries.append((f"scalar {r['type']} (GPTQ, K-quant grid)", teacher, ds, r["calib"], t["n"], t["fp_ndcg10"], t["ndcg10"], t["q_cos_fp"], pk, z["ndcg"]))
    lines = ["# Prefix KV in full precision — scalar and vector clients, torch simulation",
             "",
             "Generated by `scripts/prefix_kv_table.py`; pre-registration and reading in `research/lab_log.md` 2026-09-10. The same quantised model is "
             "evaluated three ways on the same queries: plain; `pkv0` = the query prompt's keys/values in every block taken from the fp model (the client "
             "would ship them, harrier ~2.3 MiB), the user's tokens through the quantised model; `pkv1` = only the first (sink) token from fp, the rest of "
             "the prompt through the quantised model (control separating the sink from 'an exact prompt'). Δ = paired bootstrap over queries against plain "
             "(10 000 draws, seed 0); the calibration draw is identical across the three readings, so the cosine differences are exact.",
             "",
             "| client | teacher | dataset (queries) | calib | fp nDCG | plain nDCG / cos | pkv0 nDCG Δ [CI] / cos Δ | pkv1 nDCG Δ [CI] / cos Δ | prompt tokens | q-cache control (cos to plain) |",
             "|---|---|---|---|---|---|---|---|---|---|"]
    for label, teacher, ds, calib, n, fp, nd, cos, pk, perq in entries:
        cells = []
        for k in (0, 1):
            if k not in pk:
                cells.append("–"); continue
            ndk, cosk, cosp, P, pq = pk[k]
            m, lo, hi = paired_bootstrap(pq, perq, n=N_BOOT, seed=SEED)
            cells.append(f"{ndk:.4f} ({m:+.4f} [{lo:+.4f}; {hi:+.4f}]{' *' if lo > 0 or hi < 0 else ''}) / {cosk:.4f} ({cosk - cos:+.4f})")
        P = pk[0][3] if 0 in pk else (pk[1][3] if 1 in pk else "?")
        ctrl = f"{pk[-1][2]:.4f}" if -1 in pk else "–"
        lines.append(f"| {label} | {teacher} | {ds} ({n}) | {calib} | {fp:.4f} | {nd:.4f} / {cos:.4f} | {cells[0]} | {cells[1]} | {P} | {ctrl} |")
    (ROOT / a.out).write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
